snc_redis:
    clients:
        bestselling_products:
            type: 'phpredis'
            alias: 'bestselling_products'
            dsn: '%env(REDIS_URL)%'
            options:
                prefix: '%env(REDIS_PREFIX)%%env(BUILD_VERSION)%:cache:bestselling_products:'
        doctrine_metadata:
            type: 'phpredis'
            alias: 'doctrine_metadata'
            dsn: '%env(REDIS_URL)%'
            options:
                prefix: '%env(REDIS_PREFIX)%%env(BUILD_VERSION)%:cache:doctrine:metadata:'
        doctrine_query:
            type: 'phpredis'
            alias: 'doctrine_query'
            dsn: '%env(REDIS_URL)%'
            options:
                prefix: '%env(REDIS_PREFIX)%%env(BUILD_VERSION)%:cache:doctrine:query:'
        framework_annotations:
            type: 'phpredis'
            alias: 'framework_annotations'
            dsn: '%env(REDIS_URL)%'
            options:
                prefix: '%env(REDIS_PREFIX)%%env(BUILD_VERSION)%:cache:framework:annotations:'
        global:
            type: 'phpredis'
            alias: 'global'
            dsn: '%env(REDIS_URL)%'
            options:
                prefix: '%env(REDIS_PREFIX)%'
        session:
            type: 'phpredis'
            alias: 'session'
            dsn: '%env(REDIS_URL)%'
    session:
        client: 'session'
        prefix: '%env(REDIS_PREFIX)%session:'
